# Kafka broker connection
kafka:
  brokerConnect: cluster-kafka-bootstrap:9092
# JVM options
jvm:
  opts: "-Xms32M -Xmx64M"

# Adding connection to schema registry
cmdArgs: "--schemaregistry.connect=http://apicurioregistry-app-service:8080/apis/ccompat/v7"

# Ingress resource
ingress:
  enabled: true
  ## Add ingressClassName to the Ingress
  ingressClassName: nginx
  # ingress host
  hosts:
    - kafdrop.local.test
  ## TLS Secret Name
  tls:
    - secretName: kafdrop-tls
      hosts:
        - kafdrop.local.test
  ## Default ingress path
  path: /
  ## Ingress annotations
  annotations:
    # Enable cert-manager to create automatically the SSL certificate and store in Secret
    # Possible Cluster-Issuer values:
    #   * 'letsencrypt-issuer' (valid TLS certificate using IONOS API)
    #   * 'ca-issuer' (CA-signed certificate, not valid)
    cert-manager.io/cluster-issuer: ca-issuer
    cert-manager.io/common-name: kafdrop.local.test

# Kafdrop docker images are not multi-arch. Only amd64 image is available
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64

