apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault
  namespace: kube-prom-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  namespaceSelector:
    matchNames:
      - vault
  endpoints:
    - interval: 30s
      path: /v1/sys/metrics
      params:
        format: 
          - prometheus
      port: vaultport
      scheme: https
      scrapeTimeout: 30s
      bearerTokenFile: /vault/secrets/token
      # Disable TLS verification
      tlsConfig:
        insecureSkipVerify: true