# Long-lived token for vault-auth service account.
# From Kubernetes v1.24, secrets contained long-lived tokens associated to service accounts
# are not longer created.
# See how to create it in Kubernetes documentation:
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-token-g955r
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: vault