service:
  daemon: off
  flush: 1
  log_level: info
  http_server: true
  http_listen: 0.0.0.0
  http_port: 2020
  health_check: true
  hot_reload: true
  storage.path: /var/log/fluentbit/storage
  storage.sync: normal
  storage.checksum: false
  storage.backlog:
  storage.backlog.mem_limit: 5M
  storage.metrics: true

parsers:
  - name: syslog-rfc3164-nopri
    format: regex
    regex: '/^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/'
    time_key: time
    time_format: '%b %d %H:%M:%S'
    time_keep: false


pipeline:

  inputs:
    - name: tail
      alias: input.kube
      path: /var/log/containers/*.log
      path_key: filename
      multiline.parser: docker, cri
      tag: kube.*
      db: /var/log/fluentbit/flb_kube.db
      storage.type: filesystem
      mem_buf_limit: 5MB
      skip_long_lines: true

  filters:

    - name: multiline
      match: '*'
      multiline.key_content: log
      multiline.parser: go, java, python
    
    - name: kubernetes
      match: kube.*
      buffer_size: 512k
      kube_tag_prefix: kube.var.log.containers.
      merge_log: false
      merge_log_trim: false
      merge_log_key: log_processed
      keep_log: true
      k8s-logging.parser: true
      k8s-logging.exclude: true
      labels: true
      annotations: false
    
    - name: modify
      match: kube.*
      remove: _p
      rename: log message

  outputs:
    - name: stdout
      match: '*'

    - name: forward
      match: '*'
      host: ${FLUENT_AGGREGATOR_HOST}
      port: ${FLUENT_AGGREGATOR_PORT}
      self_hostname: ${FLUENT_SELFHOSTNAME}
      shared_key: ${FLUENT_AGGREGATOR_SHARED_KEY}
      tls: true
      tls.verify: false