---

# Deploy fluent-bit as daemonSet. One POD per node
kind: DaemonSet
# Host directories containing Host and POD logs files
# Mounted into Fluent-bit DaemonSet POD
daemonSetVolumes:
  # Mount file containing host and POD logs
  # In K3S, PODS logs are located in /var/log/pods
  # Host OS logs located in /var/logs
  - name: varlog
    hostPath:
      path: /var/log
  # Mount /etc/machine-id identifying node
  # - name: etcmachineid
  #   hostPath:
  #     path: /etc/machine-id
  #     type: File
daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  # - name: etcmachineid
  #   mountPath: /etc/machine-id
  #   readOnly: true

# Environment variables used by Fluent Config files
env:
  # Forward Outpur Plugin config
  #
  # Fluentd deployment service
  - name: FLUENT_AGGREGATOR_HOST
    value: fluentd

  # Default fluentd forward port
  - name: FLUENT_AGGREGATOR_PORT
    value: "24224"
  - name: FLUENT_AGGREGATOR_SHARED_KEY
    valueFrom:
      secretKeyRef:
        name: fluent-bit-env-secret
        key: FLUENT_AGGREGATOR_SHARED_KEY

  # Setting nodeName as environment variable
  - name: FLUENT_SELFHOSTNAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  # ElasticSearch Output Plugin config
  #
  - name: FLUENT_ELASTICSEARCH_HOST
    value: "efk-es-http.elastic"
  # Default elasticsearch default port
  - name: FLUENT_ELASTICSEARCH_PORT
    value: "9200"
  # Elasticsearch user
  - name: FLUENT_ELASTICSEARCH_USER
    valueFrom:
      secretKeyRef:
        name: fluent-bit-env-secret
        key: FLUENT_ELASTICSEARCH_USER
  # Elastic operator stores elastic user password in a secret
  - name: FLUENT_ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: fluent-bit-env-secret
        key: FLUENT_ELASTICSEARCH_PASSWORD

  # Loki Output plugin config
  #
  - name: FLUENT_LOKI_HOST
    value: "loki-headless.loki"
  # Default elasticsearch default port
  - name: FLUENT_LOKI_PORT
    value: "3100"

# Environment variables used by Fluent Config files
# envFrom:
#   - configMapRef:
#       name: fluent-bit-env-configmap
#   - secretRef:
#       name: fluent-bit-env-secret


# Define configuration file in external configMap using YAML syntax
# Remove classic default configuration
config: {}
customParsers: {}
# ConfigMap mounted as /fluent-bit/etc/conf directory
existingConfigMap: fluent-bit-config

# Change args to load yaml config file instead default fluent-bit.conf
command:
  - /fluent-bit/bin/fluent-bit

args:
  - --workdir=/fluent-bit/etc
  - --config=/fluent-bit/etc/conf/fluent-bit.yaml

# Lua Scripts. ConfigMap luascripts mounted as /fluent-bit/scripts
luaScripts:
# Example lua Script for changing local time to UTC
# luaScripts:
#   adjust_ts.lua: |
#     function local_timestamp_to_UTC(tag, timestamp, record)
#         local utcdate   = os.date("!*t", ts)
#         local localdate = os.date("*t", ts)
#         localdate.isdst = false -- this is the trick
#         utc_time_diff = os.difftime(os.time(localdate), os.time(utcdate))
#         return 1, timestamp - utc_time_diff, record
#     end
    parse_kubernetes_metadata.lua: |
      function extract_app_name(tag, timestamp, record)
          if record["kubernetes"] ~= nil then
            if record["kubernetes"]["labels"]["app.kubernetes.io/name"] ~= nil then
                record["app"] = record["kubernetes"]["labels"]["app.kubernetes.io/name"]
            end
            if record["kubernetes"]["labels"]["app"] ~= nil then
                record["app"] = record["kubernetes"]["labels"]["app"]
            end
          end
          return 1, timestamp, record
      end


# Enable fluentbit instalaltion on master node
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# Init container. Create directory for fluentbit
initContainers:
  - name: init-fluentbit-directory
    image: busybox
    command: ['/bin/sh', '-c', 'if [ ! -d /var/log/fluentbit ]; then mkdir -p /var/log/fluentbit; fi ; if [ ! -d /var/log/fluentbit/tail-db ]; then mkdir -p /var/log/fluentbit/tail-db; fi ; if [ ! -d /var/log/fluentbit/storage ]; then mkdir -p /var/log/fluentbit/storage; fi']
    volumeMounts:
      - name: varlog
        mountPath: /var/log

# Enable hot-reload
# jimmidyson/configmap-reload is deployed as side-car
# By default it watches for changes in /fluent-bit/etc/conf/ (fluent-conf) and /fluent-bit/scripts (luascripts)
# If any change is detected reload endpoint is ivoked: 
# http://localhost:2020/api/v2/reload
hotReload:
  enabled: true

# Enable Prometheus operator service monitor
serviceMonitor:
  enabled: true

# Enable Grafana dashboard
dashboards:
  enabled: true
  labelKey: grafana_dashboard
  labelValue: 1
  annotations:
    grafana_folder: "Logging"