---
# fluentbit helm chart values


daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log

# Fluentbit config
config:
  # fluent-bit.config SERVICE. **NOTE 2**
  # Helm chart defaults are Ok
  # service: |
  #   [SERVICE]
  #     Daemon Off
  #     Flush 1
  #     Log_Level info
  #     Parsers_File parsers.conf
  #     Parsers_File custom_parsers.conf
  #     HTTP_Server On
  #     HTTP_Listen 0.0.0.0
  #     HTTP_Port 2020
  #     Health_Check On

  # fluent-bit.config INPUT. **NOTE 3**
  inputs: |

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser cri
        Tag kube.*
        DB /var/log/flb_kube.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines True

    [INPUT]
        Name tail
        Tag host.*
        Path /var/log/auth.log, /var/log/syslog
        DB /var/log/flb_host.db
        Parser syslog-rfc3164-nopri

  # fluent-bit.config OUTPUT **NOTE 4**
  outputs: |

    [OUTPUT]
        Name forward
        match *
        Host 192.168.56.15
        Port 24224
        Shared_Key s1cret0
        Self_Hostname fluentbit-forwarder
        Username fluentb
        Password s1cret0

  customParsers: |

    [PARSER]
        Name syslog-rfc3164-nopri
        Format regex
        Regex /^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
        Time_Key time
        Time_Format %b %d %H:%M:%S
        Time_Keep False

  filters: |

    [FILTER]
        name                  multiline
        match                 *
        multiline.key_content log
        multiline.parser      go, java, python      

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log True
        Merge_Log_Trim True
        Keep_Log False
        K8S-Logging.Parser False
        K8S-Logging.Exclude False
        Labels False
        Annotations False

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix   kubernetes_

    [FILTER]
        Name grep
        Match kube.*
        Exclude kubernetes_container_name fluent-bit

    [FILTER]
        Name modify
        Match kube.*
        Rename kubernetes_pod_name k8s.pod.name
        Rename kubernetes_namespace_name k8s.namespace.name
        Rename kubernetes_container_name k8s.container.name
        Remove kubernetes_container_image
        Remove kubernetes_docker_id
        Remove kubernetes_pod_id
        Remove kubernetes_host
        Remove kubernetes_container_hash
        Remove stream
        Remove _p
        Rename log content
        Add k8s.cluster.name mycluster

    [FILTER]
        name lua
        match host.*
        script /fluent-bit/scripts/adjust_ts.lua
        call local_timestamp_to_UTC

    [FILTER]
        Name modify
        Match host.*
        Rename message content

luaScripts:
  adjust_ts.lua: |
    function local_timestamp_to_UTC(tag, timestamp, record)
        local utcdate   = os.date("!*t", ts)
        local localdate = os.date("*t", ts)
        localdate.isdst = false -- this is the trick
        utc_time_diff = os.difftime(os.time(localdate), os.time(utcdate))
        return 1, timestamp - utc_time_diff, record
    end

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

initContainers:
  - name: init-log-directory
    image: busybox
    command: ['/bin/sh', '-c', 'if [ ! -d /var/log/fluentbit ]; then mkdir -p /var/log/fluentbit; fi']
    volumeMounts:
      - name: varlog
        mountPath: /var/log
