loki:
  # Disable multi-tenant support
  auth_enabled: false
  analytics:
    reporting_enabled: false
  server:
    log_level: info
  commonConfig:
    replication_factor: 1
  compactor:
    working_directory: /var/loki/compactor/retention
    delete_request_store: filesystem
    retention_enabled: true
  ingester:
    chunk_encoding: snappy
  limits_config:
    retention_period: 14d
  # Select filesystem storage type
  storage:
    type: filesystem  
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

# Single binary deployment
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: local-path
    size: 5Gi

gateway:
  replicas: 0
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Disable loki canary   
lokiCanary:
  enabled: false

# Disable helm-test
test:
  enabled: false

# Disable self-monitoring
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false