# Elastic search password from secret
extraEnvSecrets:
  ES_USERNAME:
    secret: es-prometheus-user-file-realm
    key: username
  ES_PASSWORD:
    secret: es-prometheus-user-file-realm
    key: password


# Elastic search URI
es:
  uri: http://efk-es-http:9200

# Logging
log:
  format: logfmt
  level: debug

# Create Service Monitor
serviceMonitor:
  enabled: true