apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-import-realm
  labels:
    app.kubernetes.io/name: keycloak-config-cli
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-config-cli
    spec:
      restartPolicy: Never
      containers:
        - name: keycloak-config-cli
          image: "docker.io/adorsys/keycloak-config-cli:6.4.0-26.1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: "IMPORT_PATH"
              value: "/config/"
            - name: "KEYCLOAK_URL"
              value: "http://keycloak-service:8080"
            - name: "KEYCLOAK_USER"
              value: "admin"
            - name: "IMPORT_VARSUBSTITUTION_ENABLED"
              value: "true"
          envFrom:
          - secretRef:
              name: kc-config-cli-config
          - secretRef:
              name: kc-config-cli-realm-vars
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: "keycloak-realm-configmap"
            defaultMode: 0555
