apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak


configMapGenerator:
  # Generate keycloak config realm
  - name: keycloak-realm-configmap
    files:
    - config/01-realm.json
    - config/02-clients.json
    - config/03-groups.json
    - config/04-users.json

resources:
  - kc-config-cli-realm-vars.yaml
  - kc-config-cli-config.yaml
  - job.yaml