# Admin user password
adminPassword: "s1cret0"
# Env secret containing SSO credentials
envFromSecret: grafana-env-secret
grafana.ini:
  server:
    domain: monitoring.localhost
    root_url: "https://%(domain)s/grafana/"
    serve_from_sub_path: false
  auth.generic_oauth:
    enabled: true
    name: Keycloak-OAuth
    allow_sign_up: true
    client_id: grafana
    # client_secret: YoR2whuGbxwOWbHqLvN5qTd99YbmxWZH
    scopes: openid email profile offline_access roles
    email_attribute_path: email
    login_attribute_path: username
    name_attribute_path: full_name
    auth_url: https://keycloak.localhost/realms/mycluster/protocol/openid-connect/auth
    token_url: https://keycloak.localhost/realms/mycluster/protocol/openid-connect/token
    api_url: https://keycloak.localhost/realms/mycluster/protocol/openid-connect/userinfo
    role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
    signout_redirect_url: https://keycloak.localhost/realms/mycluster/protocol/openid-connect/logout?client_id=grafana&post_logout_redirect_uri=https%3A%2F%2Fmonitoring.localhost%2Fgrafana%2Flogin%2Fgeneric_oauth
    tls_skip_verify_insecure: true
  log.file:
    level: debug