apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-configmap
  namespace: keycloak
data:
  cluster-realm.json: |
    {
      "realm": "mycluster",
      "accessTokenLifespan": 6000,
      "enabled": true,
      "rememberMe": true,
      "resetPasswordAllowed": true,
      "clients": [
        {
          "clientId": "proxy-oauth2",
          "name": "Proxy OAuth 2.0",
          "description": "Proxy OAuth 2.0",
          "surrogateAuthRequired": false,
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "Au03YXpH2wVGexoEtkrNoYCPQDEEFATr",
          "redirectUris": [
            "https://proxy-auth.localhost/oauth2/callback"
          ],
          "webOrigins": [
            "https://proxy-auth.localhost"
          ],
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "aud-mapper-proxy-oauth2",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "proxy-oauth2",
                "id.token.claim": "true",
                "access.token.claim": "true"
              }
            }
          ],
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "roles",
            "profile",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ],
          "access": {
            "view": true,
            "configure": true,
            "manage": true
          }
        },
        {
          "clientId": "grafana",
          "name": "Grafana",
          "description": "Grafana",
          "rootUrl": "https://monitoring.localhost/grafana",
          "adminUrl": "https://monitoring.localhost/grafana",
          "baseUrl": "https://monitoring.localhost/grafana",
          "surrogateAuthRequired": false,
          "enabled": true,
          "alwaysDisplayInConsole": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "YoR2whuGbxwOWbHqLvN5qTd99YbmxWZH",
          "redirectUris": [
            "https://monitoring.localhost/grafana/login/generic_oauth"
          ],
          "webOrigins": [
            "https://monitoring.localhost/grafana"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "publicClient": false,
          "protocol": "openid-connect",
          "fullScopeAllowed": true,
          "frontchannelLogout": true,
          "protocolMappers": [
            {
              "name": "roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-realm-role-mapper",
              "consentRequired": false,
              "config": {
                "multivalued": "true",
                "userinfo.token.claim": "true",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "roles",
                "jsonType.label": "String"
              }
            }
          ],
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "profile",
            "roles",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ],
          "access": {
            "view": true,
            "configure": true,
            "manage": true
          }
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "admin",
            "composite": false
          },
          {
            "name": "editor",
            "composite": false
          },
          {
            "name": "viewer",
            "composite": false
          },
          {
            "name": "user",
            "composite": false
          }
        ]
      },
      "users": [
        {
          "username": "ricsanfre",
          "email": "perro@mail.com",
          "enabled": true,
          "emailVerified": true,
          "credentials": [
            {
              "temporary": false,
              "type": "password",
              "value": "password"
            }
          ],
          "realmRoles": [
            "admin",
            "default-roles-mycluster"
          ]
        }
      ]
    }