apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  labels:
    cnpg.io/reload: "true"
stringData:
  username: "keycloak"
  password: "s1cret0"
#  host: "keycloak-db-rw"
#  port: "5432"
#  dbname: "keycloak"