apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: apicurio-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-4
  storage:
    size: 1Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: apicurio
      owner: apicurio
      secret:
        name: apicurio-db-secret

