---
apiVersion: v1
kind: Secret
metadata:
  name: schema-registry-secrets
stringData:
  schema-registry-password: supers1cret0
  probe-password: s1cret0
  plain-jaas.conf: |
    org.apache.kafka.common.security.scram.ScramLoginModule required username=schema-registry password=supers1cret0;

---
apiVersion: v1
kind: Secret
metadata:
  name: schema-registry-passwords
stringData:
  passwords: |
    kafdrop: supers1creto, user, developer
    probe: s1cret0, user, developer
    client: s1cret0, user, developer
