prometheus:
  prometheusSpec:
    podMetadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/role: "prometheus"
        # Using self-signed certificates, so we need to skip TLS verification
        vault.hashicorp.com/tls-skip-verify: "true"
        # Run agent as group 2000, same group used by Prometheus process. Grant read access to token file.
        vault.hashicorp.com/agent-run-as-group: "2000"