---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: efk
spec:
  version: 8.15.0
  nodeSets:
  - name: default
    count: 1    # One node elastic search cluster
    config:
      node.store.allow_mmap: false # Disable memory mapping
    volumeClaimTemplates: 
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
  auth:
    roles:
      - secretName: es-fluentd-roles-secret
      - secretName: es-prometheus-roles-secret
    fileRealm:
      - secretName: es-fluentd-user-file-realm
      - secretName: es-prometheus-user-file-realm
  http:
    tls: # Disabling TLS automatic configuration. Note(3)
      selfSignedCertificate:
        disabled: true

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: efk
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: "efk"
  http:  # NOTE disabling kibana automatic TLS configuration
    tls:
      selfSignedCertificate:
        disabled: true
