---
apiVersion: v1
kind: Secret
metadata:
  name: es-prometheus-user-file-realm
type: kubernetes.io/basic-auth
data:
  username: cHJvbWV0aGV1cw== # prometheus
  password: c3VwZXJzZWNyZXQ= # supersecret
  roles: cHJvbWV0aGV1c19yb2xl # prometheus_role

---

apiVersion: v1
kind: Secret
metadata:
  name: es-fluentd-user-file-realm
type: kubernetes.io/basic-auth
data:
  username: Zmx1ZW50ZA==   # fluentd
  password: c3VwZXJzZWNyZXQ=  # supersecret
  roles: Zmx1ZW50ZF9yb2xl # fluentd_role

