apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: mycluster
servers: ${K3D_SERVERS}
agents: ${K3D_AGENTS}
# Export traefik/nginx port
# Available at http://localhost and https://localhost
ports:
  - port: 80:80 # same as `--port '80:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
hostAliases: # /etc/hosts style entries to be injected into /etc/hosts in the node containers and in the NodeHosts section in CoreDNS
  - ip: 172.17.0.1
    hostnames:
      - keycloak.local.test
      - proxy-auth.local.test
      - monitoring.local.test
      - kibana.local.test
options:
  k3s:
    extraArgs:
      - arg: --kube-proxy-arg=metrics-bind-address=0.0.0.0
        nodeFilters:
          - server:*
          - agent:*
      - arg: --kube-controller-manager-arg=bind-address=0.0.0.0
        nodeFilters:
          - server:*
      - arg: --kube-scheduler-arg=bind-address=0.0.0.0
        nodeFilters:
          - server:*
      # Disable traefik
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      # expose etcd metrics
      - arg: --etcd-expose-metrics=true
        nodeFilters:
          - server:*