
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: test2
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./flux/terraform/test2
  sourceRef:
    kind: GitRepository
    name: k3d-recipes
    namespace: flux-system
  vars:
  - name: vault_address
    value: https://vault.local.test:8200
  - name: kubernetes_host
    value: https://kube-api.local.test:6445
  writeOutputsToSecret:
    name: tf-test2-output

  # TF_LOG debugging not supported
  # ref: https://github.com/flux-iac/tofu-controller/issues/1373
  # runnerPodTemplate:
  #   spec:
  #     env:
  #     - name: TF_LOG
  #       value: DEBUG
  #     - name: TERRAFORM_VAULT_LOG_BODY
  #       value: "true"