apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain # Plain listener for internal access
        port: 9092
        type: internal # headless service for internal access
        tls: false
        authentication:
          type: scram-sha-512 # Set authentication to scram-sha-512
      - name: tls  # TLS listerner for internal access
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512 # Set authentication to scram-sha-512
        # Use External Certificate: https://strimzi.io/docs/operators/latest/configuring.html#property-listener-config-brokerCertChainAndKey-reference
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-tls
            certificate: tls.crt
            key: tls.key
      - name: external # TLS listener for external access
        port: 9094
        type: ingress # Ingress Listener for external access
        tls: true
        authentication:
          type: scram-sha-512 # Set authentication to scram-sha-512
        configuration: # Configure Ingress resources created by Strimzi
          bootstrap:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap.local.test.
              external-dns.alpha.kubernetes.io/ttl: "60"
            host: kafka-bootstrap.example.com
          brokers:
            - broker: 0
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafa-broker-0.local.test.
                external-dns.alpha.kubernetes.io/ttl: "60"
              host: kafka-broker-0.local.test
            - broker: 1
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.local.test.
                external-dns.alpha.kubernetes.io/ttl: "60"
              host: kafka-broker-1.local.test
            - broker: 2
              annotations:
                external-dns.alpha.kubernetes.io/hostname: broker-2.local.test.
                external-dns.alpha.kubernetes.io/ttl: "60"
              host: kafka-broker-2.local.test
          # Use External Certificate
          brokerCertChainAndKey:
            secretName: kafka-tls
            certificate: tls.crt
            key: tls.key
          class: nginx
    authorization:
      type: simple # Authorization using ACLS
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
