kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: emojivoto-web
  namespace: emojivoto

spec:
  rules:
    - host: emojivoto
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc 
                port:
                  number: 80
